/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DwcButton {
    'disabled': boolean;
    'outline': boolean;
  }
  interface DwcInput {
    'disabled': boolean;
    'label': string;
    'type': string;
  }
  interface DwcLoader {}
}

declare global {


  interface HTMLDwcButtonElement extends Components.DwcButton, HTMLStencilElement {}
  var HTMLDwcButtonElement: {
    prototype: HTMLDwcButtonElement;
    new (): HTMLDwcButtonElement;
  };

  interface HTMLDwcInputElement extends Components.DwcInput, HTMLStencilElement {}
  var HTMLDwcInputElement: {
    prototype: HTMLDwcInputElement;
    new (): HTMLDwcInputElement;
  };

  interface HTMLDwcLoaderElement extends Components.DwcLoader, HTMLStencilElement {}
  var HTMLDwcLoaderElement: {
    prototype: HTMLDwcLoaderElement;
    new (): HTMLDwcLoaderElement;
  };
  interface HTMLElementTagNameMap {
    'dwc-button': HTMLDwcButtonElement;
    'dwc-input': HTMLDwcInputElement;
    'dwc-loader': HTMLDwcLoaderElement;
  }
}

declare namespace LocalJSX {
  interface DwcButton extends JSXBase.HTMLAttributes<HTMLDwcButtonElement> {
    'disabled'?: boolean;
    'outline'?: boolean;
  }
  interface DwcInput extends JSXBase.HTMLAttributes<HTMLDwcInputElement> {
    'disabled'?: boolean;
    'label'?: string;
    'type'?: string;
  }
  interface DwcLoader extends JSXBase.HTMLAttributes<HTMLDwcLoaderElement> {}

  interface IntrinsicElements {
    'dwc-button': DwcButton;
    'dwc-input': DwcInput;
    'dwc-loader': DwcLoader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


