/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DwcButton {
    'block': boolean;
    'disabled': boolean;
  }
  interface DwcCard {
    'subject': string;
  }
  interface DwcInput {
    'disabled': boolean;
    'hint': string;
    'label': string;
    'type': string;
    'value': string;
  }
}

declare global {


  interface HTMLDwcButtonElement extends Components.DwcButton, HTMLStencilElement {}
  var HTMLDwcButtonElement: {
    prototype: HTMLDwcButtonElement;
    new (): HTMLDwcButtonElement;
  };

  interface HTMLDwcCardElement extends Components.DwcCard, HTMLStencilElement {}
  var HTMLDwcCardElement: {
    prototype: HTMLDwcCardElement;
    new (): HTMLDwcCardElement;
  };

  interface HTMLDwcInputElement extends Components.DwcInput, HTMLStencilElement {}
  var HTMLDwcInputElement: {
    prototype: HTMLDwcInputElement;
    new (): HTMLDwcInputElement;
  };
  interface HTMLElementTagNameMap {
    'dwc-button': HTMLDwcButtonElement;
    'dwc-card': HTMLDwcCardElement;
    'dwc-input': HTMLDwcInputElement;
  }
}

declare namespace LocalJSX {
  interface DwcButton {
    'block'?: boolean;
    'disabled'?: boolean;
  }
  interface DwcCard {
    'subject'?: string;
  }
  interface DwcInput {
    'disabled'?: boolean;
    'hint'?: string;
    'label'?: string;
    'onValueChanged'?: (event: CustomEvent<string>) => void;
    'type'?: string;
    'value'?: string;
  }

  interface IntrinsicElements {
    'dwc-button': DwcButton;
    'dwc-card': DwcCard;
    'dwc-input': DwcInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'dwc-button': LocalJSX.DwcButton & JSXBase.HTMLAttributes<HTMLDwcButtonElement>;
      'dwc-card': LocalJSX.DwcCard & JSXBase.HTMLAttributes<HTMLDwcCardElement>;
      'dwc-input': LocalJSX.DwcInput & JSXBase.HTMLAttributes<HTMLDwcInputElement>;
    }
  }
}


