/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface Button {
    'disabled': boolean;
    'text': string;
  }
}

declare global {


  interface HTMLDwcButtonElement extends Components.Button, HTMLStencilElement {}
  var HTMLButtonElement: {
    prototype: HTMLButtonElement;
    new (): HTMLButtonElement;
  };
  interface HTMLElementTagNameMap {
    'dwc-button': HTMLButtonElement;
  }
}

declare namespace LocalJSX {
  interface Button extends JSXBase.HTMLAttributes<HTMLButtonElement> {
    'disabled'?: boolean;
    'text'?: string;
  }

  interface IntrinsicElements {
    'button': Button;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


